### ISSUE TITLE
Replace VersionPress archive with unpacked version (and adjust installation scripts)

### ISSUE THREAD

**Issue by pschoffer** [pschoffer/gitpress#3]
Why?
- So that we can change the version press behavior directly (or not)

Probably using something like `git subtree`.

**Comment by forgondolin** [comment]
I'm a little confused by this one, isn't the same thing in mu-plugins issue?

**Comment by pschoffer** [comment]
Yep, this is like a sub-issue i guess. This is better to be done before. 

So the idea here is that instead of zip file we would have all the source code for the plugin (which means we don't need to do ` wp plugin install /usr/src/versionpress/*.zip --activate --allow-root` in the utils.sh, but just the WP activation I guess). We will still keep it under regular plugins and need to do:
`wp vp activate --allow-root`

**Comment by pschoffer** [comment]
This moved to a https://github.com/pschoffer/gitpress/issues/5
