### ISSUE TITLE
Simple Build Pipeline to build docker image

### ISSUE THREAD

**Issue by pschoffer** [pschoffer/gitpress#6]
Probably `circleci` or something just to see that docker build won't fail to feel safer before merge.

**Comment by enflo** [comment]
Can I help you, can you assign me the issue?

**Comment by pschoffer** [comment]
Hi @enflo thanks for checking this out. This was already done in https://github.com/pschoffer/gitpress/pull/12 by @forgondolin. (@forgondolin , could you please reference an issue in the next PRs, then it should be shown here as well).

@forgondolin  is also looking into https://github.com/pschoffer/gitpress/issues/5 and https://github.com/pschoffer/gitpress/issues/3 as those are related. 

But @enflo you can pick up this one - https://github.com/pschoffer/gitpress/issues/1 if you want to. After we are done with moving plugin to mu-plugins, I have few more tasks in mind to put here, so feel free to collaborate on https://github.com/pschoffer/gitpress/issues/5 and https://github.com/pschoffer/gitpress/issues/3  with @forgondolin  as well.
